console.log('Математика:');
console.log('Сложение:','5 + 2 = ',5+2);
console.log('Вычетание:','5 - 2 = ',5-2);
console.log('Умножение:','7 + 8 = ',7*8);
console.log('Деление:','10 / 2 = ',10/2);
console.log('Взятие остатка:','5 / 2 = ',5%2);
console.log('Возведение в степень:','2^5 = ',2**5);
console.log('Сложение строк:');
console.log('Абрамук ' + 'Дмитрий');
console.log('Инкремент/декремент:');
let i = 1;
console.log(i++,i--,++i,--i);
console.log('Операторы сравнения:');
console.log('5 > 10', 5>10);
console.log('5 >= 10', 5>=10);
console.log('5 < 10', 5<10);
console.log('5 <= 10', 5<=10);
console.log('5 != 10', 5!=10);
console.log('null == undefined', null==undefined);
console.log('null === undefined', null===undefined);